apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinsmagning-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: backend
          image: registry.jazper.dk/wine-backend:latest
          ports:
            - containerPort: 3000
        - name: reactsk
          image: registry.jazper.dk/reactsk:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: regcred